### ISSUE TITLE
Make Regex in RVD Control more intuitive

### ISSUE THREAD

**Issue by croufay** [RestComm/visual-designer#110]
@otsakir, there seem to be a little problem with the Regex match in the RVD control
use case, I want to check the content of an SMS to see if it contains a certain string and then act according, the regex doesn't work.

![rvd-control](https://cloud.githubusercontent.com/assets/8916055/24161574/6979f10a-0e2a-11e7-9fb7-4b9bfdc3a654.png)

If the text to check says "control", then it works
12:54
but searching a full sentence like in the screenshot doesn't work

@charles, the regex validation is strict and for a good reason since the behavior of the application depends heavily on it.
You'll have to change your regex string to the following:
^.*control.*$ (edited)
the above should work like 'contains'

Hean : maybe it makes  sense to offer a regex expression builder at some point that would generated exressions on the fly. It could have macro statements like 'contains' or 'startsWith' and save the user from the regex magic. (edited)

**Comment by otsakir** [comment]
Related to #102

**Comment by otsakir** [comment]
already fixed
