### ISSUE TITLE
RVD/Olympus is using port 5082 for WSS when it should be using 5083

### ISSUE THREAD

**Issue by croufay** [RestComm/visual-designer#111]
PrivateJainSipClientConnector:checkConfiguration(): configuration.sipRegisterMode:true 
	[PrivateJainSipClientConnector.checkConfiguration (https://companyName.com/olympus/resources/js/mobicents-libs/WebRTComm.js:1445:11)]
jain-sip.js:25448 WebSocket connection to 'wss://companyName.com:5082/' failed: WebSocket opening handshake timed out
WSMessageChannel.createWebSocket @ jain-sip.js:25448
WSMessageChannel @ jain-sip.js:25439
WSMessageProcessor @ jain-sip.js:25659
SipStackImpl.createListeningPoint @ jain-sip.js:31692
PrivateJainSipClientConnector.open @ WebRTComm.js:1207
WebRTCommClient.open @ WebRTComm.js:4594
$scope.connect @ sign-in.js:122
$parseFunctionCall @ angular.js:12336
callback @ angular.js:21422
$eval @ angular.js:14388
$apply @ angular.js:14487
(anonymous) @ angular.js:21427
dispatch @ jquery.js:4430
elemData.handle @ jquery.js:4116
WebRTComm.js:4925 2017-21-03 13:41:12.816 WSMessageChannel:createWebSocket(): websocket connection has failed:[object Event] 

Stack trace: 
    at commonLog (https://companyName.com/olympus/resources/js/mobicents-libs/WebRTComm.js:4884:10)
    at Object.console.error (https://companyName.com/olympus/resources/js/mobicents-libs/WebRTComm.js:4957:4)
    at WebSocket.websocket.onerror (https://companyName.com/olympus/resources/js/mobicents-libs/jain-sip.js:25466:17)
commonLog @ WebRTComm.js:4925
console.error @ WebRTComm.js:4957
websocket.onerror @ jain-sip.js:25466
WebRTComm.js:4925 2017-21-03 13:41:12.817 PrivateJainSipClientConnector:processConnectionError(): SIP connection has failed, error:[object Event] 
	[PrivateJainSipClientConnector.processConnectionError (https://companyName.com/olympus/resources/js/mobicents-libs/WebRTComm.js:1571:10)]

**Comment by ammendonca** [comment]
Not applicable to RVD and has been fixed in Olympus with configuration file.
