### ISSUE TITLE
Visualization issue when importing several projects

### ISSUE THREAD

**Issue by FerUy** [RestComm/visual-designer#124]
When several projects are imported in RVD, initially it shows everyone several times, as can be seen in attached image. Not a big deal, a refresh of the browser solves the visualization problem, however, it could lead customers to confusion at a first glance.
![rvd_import_issue](https://cloud.githubusercontent.com/assets/14883482/24935381/1efbc8a4-1ef8-11e7-9b0d-c5c07175f6e2.png)

**Comment by otsakir** [comment]
Interesting finding @FerUy. In case you experience it again please test the following:

_Hover over the project labels that are duplicated. The project/application SID should be hinted. Please confirm it's the same_

**Comment by FerUy** [comment]
@otsakir confirmed as can be seen in attached image.
![rvd_import_issue_hover_over_replicated-rvd](https://cloud.githubusercontent.com/assets/14883482/24988920/6029d0c2-1fdf-11e7-9e27-d7a36323a4eb.png)
