### ISSUE TITLE
Download Project link does not work in Safari

### ISSUE THREAD

**Issue by scottbarstow** [RestComm/visual-designer#125]
You click the button and nothing happens. 

This is the case in either the project list or in the project page itself.

The JS Error console shows the following error:

Failed to load resource: Frame load interrupted

Running macos 10.12.3 and Safari Version 10.0.3 (12602.4.8)

**Comment by davidpelayo** [comment]
[Related to this discussion](https://github.com/eligrey/FileSaver.js/issues/215#issuecomment-302668297).

Now on latest Safari release, this gets fixed. See [more info here](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html).

**Comment by otsakir** [comment]
Closing issue
