### ISSUE TITLE
Remove root application from wildfly in docker image

### ISSUE THREAD

**Issue by otsakir** [RestComm/visual-designer#166]
Docker image contains wildfly administration application. It needs to be removed.

**Comment by deruelle** [comment]
We should probably make RVD the root application.

**Comment by otsakir** [comment]
@deruelle i agree in principle. 

I'm a little worried about removing the /restcomm-rvd/ prefix altogether as we speak. There are some aspects that will need to taken care of and some more work involved too.

Shall i bite the bullet ?

**Comment by otsakir** [comment]
Btw, ROOT application is already removed from the docker image. It's the _welcome-content_ that's still there.

**Comment by otsakir** [comment]
For now, I've established a redirect from /index.html of wildfly to /restcomm-rvd/.

**Comment by deruelle** [comment]
Thanks @otsakir. Let's create another issue to make it replace root and track that down separately with lower priority

**Comment by otsakir** [comment]
ok @deruelle, agreed  - https://github.com/RestComm/visual-designer/issues/171
