### ISSUE TITLE
rvd.xml file external service timeout not working

### ISSUE THREAD

**Issue by croufay** [RestComm/visual-designer#202]
full details of the issue is here
https://github.com/RestComm/Restcomm-Connect/issues/2410

**Comment by otsakir** [comment]
@croufay , please take into account latest comment on #2410 - https://github.com/RestComm/Restcomm-Connect/issues/2410#issuecomment-325275040. 

Are you still still positive that the timeout does not work ?

**Comment by otsakir** [comment]
Manually tested timeout setting. Everything works fine. Closing this as invalid.
