### ISSUE TITLE
Create connection pooling for External Services

### ISSUE THREAD

**Issue by FerUy** [RestComm/visual-designer#222]

**Comment by FerUy** [comment]
@jaimecasero, this had been added to the Voice and Video SIP Routing Squad by @deruelle, thus unassigned myself and assigned it to you.

**Comment by otsakir** [comment]
@FerUy , can you provide some more information about this issue ?

**Comment by jaimecasero** [comment]
@otsakir the idea is to configure http clients to use proper conenction pooling. Im doing some research on current usage at https://docs.google.com/document/d/1GZz0hPZzoL410uMWObTiWVJQgYiSaN7F2C2Qz5R0lqg/edit . Basically by default http client has 20 connections, and 2 per target, which may be to low in most scenarios. The idea would be to allow proper configuration of conn per route , max connections. The major issue i see here is that for some reason we dont reuse http client instances, but build a new one every time we send a request, this is heavy and will prevent any proper conn management to happen
