### ISSUE TITLE
ExternalServices: Provide support for custom headers

### ISSUE THREAD

**Issue by gvagenas** [RestComm/visual-designer#235]
... such as Authorization header

**Comment by deruelle** [comment]
@otsakir what is the effort to enable that ? I manage to workaround it by using AWS API Gateway but if it could work in RVD that would be much easier

**Comment by otsakir** [comment]
@gvagenas, @deruelle , for ES authorization there are already usename/password as shown here:

![es_auth](https://user-images.githubusercontent.com/8972800/31068663-a5c3b738-a761-11e7-8b7d-a6f2084080b4.png)

There is also this older issue regarding custom headers. I didn't see much interest back then so it was left in the backlog:

https://github.com/RestComm/visual-designer/issues/82

Shall i bring #82 back from the dead ? :-)

**Comment by deruelle** [comment]
@otsakir username and password is not possible in this case so yes.

**Comment by otsakir** [comment]
After discussion it seems, we need generic header support. Currently generated authentication headers don't support Bearer authentication.

**Comment by deruelle** [comment]
@otsakir when do we plan this one in the backlog ?
