### ISSUE TITLE
Video support for Dial/Client and Dial/SipURI

### ISSUE THREAD

**Issue by otsakir** [RestComm/visual-designer#237]
Support video options for the remaining dial nouns. In both cases we're talking about _enable_, _resolution_ and and _overlay_ attributes. 

New RCML should look like this for Client…
```
<Response>
   <Dial>
      <Client name="alice">
         <Video enable="true" resolution="720p" overlay="text"></Video>
      </Client>
   </Dial>
</Response>
```
and like this for Sip URI…
```
<Response>
   <Dial>
      <Sip name="sip:username@ipaddress:port">
         <Video enable="true" resolution="720p" overlay="text"></Video>
      </Sip>
   </Dial>
</Response>
```

**Comment by otsakir** [comment]
@ghjansen , seems like _enable_ and _overlay_ options are already in place for both Client and SipUri. I'll just add _resolution_.

**Comment by ghjansen** [comment]
thank you @otsakir ! :)
