### ISSUE TITLE
Greek characters in project name are not stored correctly

### ISSUE THREAD

**Issue by otsakir** [RestComm/visual-designer#245]
Here is what happens if the project name consists of greek (or other UTF-8 character possibly) characters: 

![greek_project_name_bug](https://user-images.githubusercontent.com/8972800/31885622-ca7d6e7c-b7f9-11e7-8d6c-c35e1973694a.png)

**Comment by atsakiridis** [comment]
@otsakir FYI could be related to https://telestax.atlassian.net/browse/INFRA-280. We can test again, once that is fixed to see if this is also fixed

**Comment by otsakir** [comment]
great @atsakiridis
