### ISSUE TITLE
Outbound Caller ID rules for WebRTC Demo

### ISSUE THREAD

**Issue by marca56** [RestComm/visual-designer#255]
* if a DID is assigned to a username, 
** then the DID should be sent as caller ID on calls to the PSTN
** then the username should be sent as caller ID on P2P calls
* if no DID is assigned to a username, 
** then NULL (meaning empty string) should be sent as caller ID on calls to the PSTN
** then the username should be sent as caller ID on P2P calls

These rules work for RCML apps, but should also work for WebRTC Demo calls :(

**Comment by anhntnguyen** [comment]
https://telestax.atlassian.net/browse/RESTCOMM-1177

**Comment by ammendonca** [comment]
Issue moved to [RestComm/olympus #149](https://github.com/RestComm/olympus/issues/149) via [**ZenHub**](https://www.zenhub.com/)
