### ISSUE TITLE
Spelling error on in Numbers, SMS, Advanced TAB

### ISSUE THREAD

**Issue by jjsenay** [RestComm/visual-designer#273]
All,

In RVD under the numbers tab where you set the SMS app for the number, under the advanced feature TAB it reads SMS Call Back URL, It should read SMS **F**all Back URL

Thanks

JJS

**Comment by ammendonca** [comment]
Issue moved to [RestComm/Restcomm-Connect #2725](https://github.com/RestComm/Restcomm-Connect/issues/2725) via [**ZenHub**](https://www.zenhub.com/)
