### ISSUE TITLE
Remove start up module

### ISSUE THREAD

**Issue by otsakir** [RestComm/visual-designer#28]
_From @ipsilantide on February 21, 2017 12:7_

@ipsilantide commented on [Wed Oct 12 2016](https://github.com/RestComm/graphics-design/issues/17)

Remove the start up module. and put it as an option in the modules dropdown to save space.

---

@ipsilantide commented on [Tue Feb 21 2017](https://github.com/RestComm/graphics-design/issues/17#issuecomment-281325979)

to think about

_Copied from original issue: RestComm/Restcomm-Connect#1877_

**Comment by mmgc84** [comment]
Hi there!

@ipsilantide: What are you trying to achieve here? You want to get rid of the entire "Welcome" module or just the Say/USSD Mesagge/SMS? I would like to help with this.

Regards
Marcelo

**Comment by otsakir** [comment]
Hi @mmgc84! Thanks for stepping up and getting involved. 

This issue is still under consideration as RVD will undergo a big UI revamp. Just incorporating the startup module in the list may not be the way to go.

There are other issues however where you could definitely get your hands dirty:

https://github.com/RestComm/visual-designer/issues/64
https://github.com/RestComm/visual-designer/issues/19
https://github.com/RestComm/visual-designer/issues/3

Ping me on github if you  need any further help ;-)

**Comment by otsakir** [comment]
@ipsilantide , shall i close this? 

Removing the button could be part of a revamp but we can't just not allow changing the startup module.  Some way to do it has to exist.

**Comment by otsakir** [comment]
closing issue
