### ISSUE TITLE
RCMLSerializer hotspot

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/visual-designer#319]
We should be reusing Xtream instance, instead of creating new one per request, this is introducing so much overhead

as per doc xtream is threadsafe and maybe reused
https://x-stream.github.io/javadoc/com/thoughtworks/xstream/XStream.html

https://github.com/RestComm/visual-designer/blob/master/designer/src/main/java/org/restcomm/connect
/rvd/interpreter/serialization/RcmlSerializer.java#L47

i guess a simple static instance may work, although some other kind of injection would be recomended

**Comment by otsakir** [comment]
@jaimecasero , are we talking about the same thing ?

https://github.com/RestComm/visual-designer/issues/142

**Comment by jaimecasero** [comment]
i think is same thing yes...
