### ISSUE TITLE
Use different maven artifactId for enterprise Designer

### ISSUE THREAD

**Issue by otsakir** [RestComm/visual-designer#347]
Make sure all places that retrieve enterprise Designer through maven are updated accordingly.

**Comment by gsaslis** [comment]
@otsakir so, are you talking about something like `org.restcomm` vs. `com.restcomm` as the group id ?

**Comment by otsakir** [comment]
@gsaslis , i was thinking about changing the artifactId but what you suggest may be more appropriate

**Comment by otsakir** [comment]
@Yorgos, new maven name! For community:

<groupId>org.restcomm<groupId>
<artifactId>visual-designer</artifactId>

For commercial

<groupId>com.restcomm<groupId>
<artifactId>visual-designer</artifactId>
