### ISSUE TITLE
Decouple RVD storage layer from filesystem

### ISSUE THREAD

**Issue by otsakir** [RestComm/visual-designer#35]
_From @otsakir on October 28, 2016 8:50_

Currently RVD access the filesystem through a concrete class named WorkspaceStorage. We need to hide this implementation behind an interface so that it's possible to use other storage solutions besides filesystem.

Relates to #870 and #1280

_Copied from original issue: RestComm/Restcomm-Connect#1514_

**Comment by gsaslis** [comment]
@otsakir LOVE IT! <3 👏
