### ISSUE TITLE
Re-evaluate restcomm location dynamic resolving 

### ISSUE THREAD

**Issue by otsakir** [RestComm/visual-designer#353]
Dynamic resolving is a new but disabled feature of Designer that determines the location of restcomm from URL instead of configuration. We need to run some last checks before enabling this in production as it is very crucial.

**Comment by gsaslis** [comment]
@otsakir where can i learn more about this?

**Comment by otsakir** [comment]
@gsaslis , there is some info on #223, #231. 

This is about how Designer will find where restcomm is in order to consume its API (for authentication, WebTrigger etc.). The oldschool/existing approach is to use either hardcoded value in configuration (restcommBaseUrl in rvd.xml) or if this does not exist use the auto-detected value from the JBoss connectors. 

What has been implemented is to use the information from the request HTTP headers instread. This is 'dynamic restcomm location resolving'. I'm a little worried about LB's, http/https scheme information that might be changed lost. Thus i created this issue to re-evaluate. 

If everything proves safe, i'll proceed to enabling dynamic resolving from rvd.xml in cloud.

**Comment by gsaslis** [comment]
got ya! thanks a lot for taking the time!

I was actually looking for sth like this ;)

**Comment by otsakir** [comment]
Ι spotted a glitch in this mechanism. 

It's in case a proxy server stands in front and changes requests scheme from https to http while forwarding. This will fool Designer in believing that it can find restcomm (API) at http:// scheme instead of the scheme used in the browser. 

There are two ways to see this:
1) Do use plaintext http to get back to restcomm. At the end, if Designer works with http maybe restcomm does too.
2) Designer should somehow find the scheme from the actual user request. It should contact restcomm using the same scheme the user used. That's the ultimate piece of information.

**Comment by otsakir** [comment]
Looks like there is already a convention for an http header that conveys the scheme:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

If we make the proxy include this piece of information in the request, Designer could take into account when resolving restcomm location.
