### ISSUE TITLE
visual-designer.war not found

### ISSUE THREAD

**Issue by jaimet561** [RestComm/visual-designer#360]
Attempting to install Restcomm-Connect, following the instructions on https://www.restcomm.com/docs/connect/configuration/How%20to%20build%20Restcomm-Connect%20from%20source.html
I get error:
BUILD FAILED
Warning: Could not find file PATH/Restcomm-Connect/release/visual-designer.war to copy.

Please note that the I changed the path of RESTCOMM_HOME to match the path in my machine.

**Comment by PC1989** [comment]
Hello 

I am facing with same problem. Do you have some hint to fix it ?
