### ISSUE TITLE
RVD home page does not suggest how to edit existing apps

### ISSUE THREAD

**Issue by ivelin** [RestComm/visual-designer#4]
The current RVD home screen shows how to create a new app, but it does not help the user see how to find and edit existing apps. See screenshot.

<img width="839" alt="screen shot 2017-02-12 at 1 26 45 pm" src="https://cloud.githubusercontent.com/assets/2234901/22866207/1c909490-f127-11e6-89ba-b326a5a1f0ca.png">

**Comment by ipsilantide** [comment]
@ivelin I agree we should rethink that during the UX revamp of the RVD. Indeed it seems like the user is able only to start a project.

**Comment by ipsilantide** [comment]
@otsakir @deruelle  Maybe we need a UX label here too :)

**Comment by deruelle** [comment]
@ipsilantide do you have rights to create one at https://github.com/RestComm/visual-designer/labels ?

**Comment by ipsilantide** [comment]
Yes I just made one

**Comment by otsakir** [comment]
Closing the issue as it's no longer applicable
